sudo: required

services:
  - docker

install:
  - sudo sysctl -w vm.max_map_count=262144

before_script:
  - docker build .

script:
  - ./test/tests

after_success:
  - bash ./scripts/ci-deployment/deploy.sh
