sudo: required

services:
  - docker

install:
  - sudo sysctl -w vm.max_map_count=262144

script:
  - docker build .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./scripts/ci-deployment/docker_ci.sh
