version: '2'

services:

  travis-tests:
    build: .
    command: bash /scripts/test
    user: root
    volumes:
      - ./scripts/test:/scripts/test
    links:
      - profiles-db-elastic:es

  profiles-db-elastic:
    build: .
