version: '2.1'

services:

  profiles-elastic:
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    build:
      context: .
    ports:
      - "${ES_PORT:-9200}:9200"
    command: ["bin/elasticsearch"]
    volumes:
      - esdata1:/data

volumes:
  esdata1:
