version: '2.1'

services:

  profiles-elastic:
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    build:
      context: .
    ports:
      - "${ES_PORT:-9200}:9200"
    command: ["bin/elasticsearch"]
    volumes:
      - esdata1:/data

volumes:
  esdata1:
