version: '2.0'

services:

  profiles-elastic:
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    build:
      context: .
    volumes:
      - ./config/:/usr/share/elasticsearch/config
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    container_name: profiles-elastic
    command: ["bin/elasticsearch"]
