version: '2'

services:

  container-tests:
    build: .
    command: bash /scripts/container-tests
    user: root
    volumes:
      - ./scripts/container-tests:/scripts/container-tests
    links:
      - profiles-db-elastic:es

  profiles-db-elastic:
    build: .
