#!/bin/bash
echo 'Starting to format ./data/input/gp-data-merged.json ready for ES ingestion'
mkdir -p ./data/output
jq -c '.[]  | .id = ._id | del (._id) | del (.openingTimes) | {"index": {"_index": "profiles", "_type": "gps", "_id": .id}}, .' ./data/input/gp-data-merged.json > ./data/output/gp-data-bulk-insert.json
echo 'Finished formatting ./data/input/gp-data-merged.json ready for ES ingestion'
