#!/bin/bash
echo "Set Docker host's max_map_count for ES"
open "https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode"
git submodule init
git submodule update
