#!/bin/bash
echo 'Starting to format data/input/gp-data-merged.json ready for ES ingestion'
jq -c '.[]  | .id = ._id | del (._id) | del (.openingTimes) | {"index": {"_index": "profiles", "_type": "gps", "_id": .id}}, .' data/input/gp-data-merged.json > data/output/gp-data-bulk-insert.json
echo 'Finished formatting data/input/gp-data-merged.json ready for ES ingestion'

echo 'Stop and remove any existing project containers, networks, etc.'
docker-compose down -v

echo 'Start up ES contatiner'
docker-compose up --build --force-recreate profiles-elastic
