#!/bin/bash
docker-compose -p es -f docker-compose-tests.yml down -v
docker-compose -p es -f docker-compose-tests.yml build container-tests
docker-compose -p es -f docker-compose-tests.yml run container-tests
